version: "3.5"

services:
  dev_nginx:
    container_name: dev_nginx
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./.docker/nginx/logs:/var/log/nginx
      - ./:/var/www
    restart: on-failure
    tty: true
    networks:
      default:
        ipv4_address: 172.28.1.1

  dev_postgres:
    container_name: dev_postgres
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
      - .docker/postgres/scripts:/etc/postgresql/scripts
    environment:
      POSTGRES_DB: validacao
      POSTGRES_USER: ecodedevteam
      POSTGRES_PASSWORD: ecodedevteam123
    restart: on-failure
    tty: true
    networks:
      default:
        ipv4_address: 172.28.1.2

  dev_mysql:
    container_name: dev_mysql
    build:
      context: .docker/mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: on-failure
    tty: true
    networks:
      default:
        ipv4_address: 172.28.1.3

  dev_php:
    container_name: dev_php
    build:
      context: .docker/php7.4
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    volumes:
      - ./:/var/www
    env_file: .env
    restart: on-failure
    tty: true
    networks:
      default:
        ipv4_address: 172.28.1.4
        
networks:
  default:
    name: dev-network
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16